apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
          tier: php
spec:
  ports:
  - port: 80
  selector:
    tier: php
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-pv-claim
  labels:
    tier: php
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: php
  labels:
    tier: php
spec:
   replicas: 2
   selector:
    matchLabels:
      tier: php
   strategy:
    type: Recreate
   template:
    metadata:
      labels:
        tier: php
    spec:
      containers:
      - image: devil00/task6-php
        name: php
        ports:
        - containerPort: 80
          name: php
        volumeMounts:
        - name: php-persistent-storage
          mountPath: /var/log/httpd
      volumes:
      - name: php-persistent-storage
        persistentVolumeClaim:
          claimName: php-pv-claim
